SELECT
    C.COUNTRY_NAME,
    L.CITY,
    D.DEPARTMENT_NAME,
    E.EMPLOYEE_ID,
    E.FIRST_NAME,
    E.LAST_NAME,
    M.FIRST_NAME as MGR_FIRST_NAME,
    M.LAST_NAME as MGR_laST_NAME,
    M.MANAGER_ID
FROM
    HR.COUNTRIES   C
    LEFT JOIN HR.LOCATIONS   L ON C.COUNTRY_ID = L.COUNTRY_ID
    LEFT JOIN HR.DEPARTMENTS D ON L.LOCATION_ID = D.LOCATION_ID
    full JOIN HR.EMPLOYEES   E ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    LEFT JOIN HR.EMPLOYEES   M ON E.MANAGER_ID = M.EMPLOYEE_ID
ORDER BY
    E.EMPLOYEE_ID;


-- select * from hr.employees order by employee_id;